# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiagiOSTechTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiagiOSTechTest
  pod 'Alamofire'
  pod 'SnapKit'

  target 'DiagiOSTechTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
